apiVersion: apps/v1
kind: Deployment
metadata:
  name: resansible-deployment
  namespace: resansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resansible
  template:
    metadata:
      labels:
        app: resansible
    spec:
      securityContext:
        runAsUser: 10000
        runAsNonRoot: true
      containers:
      - name: resansible
        image: bacinka/resansible
        ports:
        - containerPort: 22
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        volumeMounts:
        - name: ssh-volume
          mountPath: /root/.ssh/id_rsa
          readOnly: true
        - name: backups-volume
          mountPath: /.backups
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - NET_RAW
            - ALL
      volumes:
      - name: ssh-volume
        persistentVolumeClaim:
          claimName: ssh-pvc
      - name: backups-volume
        persistentVolumeClaim:
          claimName: backups-pvc
      automountServiceAccountToken: false
