apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssh-pvc
  namespace: resansible
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc
  namespace: resansible
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
