---
- name: Create backup 
  hosts: localhost
  tasks:
    - name: Get timestamp
      shell: "date +%Y-%m-%d_%H-%M-%S"
      register: tstamp

    - name: Create backup directory
      file:
        path: "~/.backups"
        state: directory
        mode: '0755'

    - name: Create timestamp directory
      file:
        path: "~/.backups/{{ tstamp.stdout }}"
        state: directory
        mode: '0755'

    - name: Get current user's home directory path
      command: echo $HOME
      register: home_dir

    # - name: Archive Home Directory
    #   ansible.builtin.archive:
    #     path:
    #       - "{{ home_dir.stdout }}"
    #     dest: "~/.backups/{{ tstamp.stdout }}/home_backup.tar.gz"
    #     format: gz
    #     exclude_path: "{{ home_dir.stdout }}/.backups"

    - name: Archive Documents Directory
      ansible.builtin.archive:
        path:
          - "{{ home_dir.stdout }}/Documents"
        dest: "~/.backups/{{ tstamp.stdout }}/documents_backup.tar.gz"
        format: gz

    - name: Create apt packages backup
      shell: "apt-mark showmanual > ~/.backups/{{ tstamp.stdout }}/apt_packages.txt"

    - name: Create VS snap packages backup
      shell: "snap list | tail -n+2 | cut -d' ' -f1 > ~/.backups/{{ tstamp.stdout }}/snap_packages.txt"

    - name: Create VS Code extensions backup
      shell: "code --list-extensions > ~/.backups/{{ tstamp.stdout }}/vscode_extensions.txt"
