---
- name: Restore from specified backup
  hosts: localhost
  gather_facts: yes
  vars:
    backup_dir: "~/.backups/{{ backup_name }}"
  tasks:
    - name: Ensure specified backup directory exists
      assert:
        that:
          - backup_dir != ''

    # - name: Restore Home directory
    #   unarchive:
    #     src: "{{ backup_dir }}/home_backup.tar.gz"
    #     dest: "~/.backups/"
    #     remote_src: yes

    - name: Restore Documents directory
      unarchive:
        src: "{{ backup_dir }}/documents_backup.tar.gz"
        dest: "~/.backups/"
        remote_src: yes
    
    - name: Check if apt is installed
      command: which apt
      register: apt_installed
      ignore_errors: yes

    - name: Install apt packages
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ lookup('file', backup_dir + '/apt_packages.txt').splitlines() }}"
      when: apt_installed.rc == 0

    - name: Check if snap is installed
      command: which snap
      register: snap_installed
      ignore_errors: yes

    - name: Install snap packages
      become: yes
      shell: "snap install {{ item }}"
      loop: "{{ lookup('file', backup_dir + '/snap_packages.txt').splitlines() }}"
      when: snap_installed.rc == 0

    - name: Check if VS Code is installed
      command: which code
      register: vscode_installed
      ignore_errors: yes

    - name: Install VS Code extensions
      shell: "code --install-extension {{ item }}"
      loop: "{{ lookup('file', backup_dir + '/vscode_extensions.txt').splitlines() }}"
      when: vscode_installed.rc == 0
